# Create 3 nginx pods in a replica set

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: trail8
  labels:
    name: replica
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
       app: nginx
  template:
    metadata:
      labels:
        env: dev
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx



      

