# create a replicaset with pod spec running alpine container without any args

---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: trail11
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      name: replicaex   
    spec:
      containers:
        - name: alpine
          image: alpine
          resources:
            limits:
              cpu: 500m
              memory: 256Mi

        

    
  
  
  
  
