# Create a service to forward the request to 80 port of nginx pods with label app : nginx

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: trail12
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: replica
      labels:
        env: dev
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx


---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80





