# Create a pod manifest with the following labels
# env = dev
# app = nginx
# version = 1.0


---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    env: dev
    app: nginx
    version: "1.0"
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
   
